apiVersion: v1
kind: Service
metadata:
  name: go-microservice
  labels:
    app: go-microservice
spec:
  selector:
    app: go-microservice
  ports:
    - name: http
      port: 8080
      targetPort: 8080
    - name: grpc
      port: 50051
      targetPort: 50051
  type: ClusterIP